---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    checks:
      Similar code:
        enabled: false
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-85
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/
