AllCops:
  Exclude:
    - splitta.gemspec
    - Rakefile

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/ExtraSpacing:
  Enabled: false

Layout/LineLength:
  Max: 120
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Max: 50
  Enabled: false

Metrics/BlockLength:
  Max: 50
  Enabled: false

Metrics/ClassLength:
  Max: 50
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 30
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Enabled: false

Metrics/ModuleLength:
  Max: 1000
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 30
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RescueModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/ZeroLengthPredicate:
  Enabled: false
